Move catsmtl interop
tofu-tf/tofu pull request #719
Opened 2021-07-20 16:12 UTC by Ssstlis

Closes #718

2021-07-20 17:27 UTC, FunFunFine approved these changes

2021-07-21 15:02 UTC, catostrophe requested changes

2021-07-21 15:02 UTC, catostrophe commented on README.md
> +  * `tofu-kernel-cats-mtl` for interop between `tofu-core` and [Cats MTL](https://github.com/typelevel/cats-mtl)
```suggestion
  * `tofu-kernel-cats-mtl` for interop between `tofu-kernel` and [Cats MTL](https://github.com/typelevel/cats-mtl)
```

2021-07-21 15:03 UTC, catostrophe approved these changes

2021-07-22 16:44 UTC, Odomontois approved these changes

2021-07-22 16:44 UTC, merged